import os.path
import argparse
from pathlib import Path

import generators.Cpp17.meson
import generators.embedded.arduino

# comments mostly generated by ChatGPT from openai and tweaked by me

# This block of code will only be executed if this script is run directly,
# rather than being imported by another script.
if __name__ == "__main__":
    # define the message that will be displayed when the user runs the script with the -h flag
    msg = "A code generator for the unit system library.\n"
    msg += "This script generates all units and contains all of the unit definitions."

    # create an ArgumentParser object to parse command line arguments
    parser = argparse.ArgumentParser(
        description=msg
    )

    # define the 'genArduino' argument, which is a flag that indicates whether
    # the output should be generated for Arduino
    parser.add_argument(
        "--arduino",
        help="Generate the output for arduino",
        required=False,
        default=False,
        dest='genArduino',
        action='store_true'
    )

    # define the 'outDir' argument, which is optional, should be a string, and has a default value of ''
    parser.add_argument(
        "--outDir",
        "-o",
        help="Put all files in the same given directory. This overwrites the baseDir.",
        required=False,
        default='',
        dest='outDir',
        type=str,
    )

    # define the 'printOutFiles' argument, which is a flag that indicates whether
    # the generated files should be printed
    parser.add_argument(
        "--printOutFiles",
        help="set to true if the generated file should be print",
        required=False,
        default=False,
        dest='printOutFiles',
        action='store_true',
    )

    # parse the command line arguments
    args = vars(parser.parse_args())

    # get the directory containing the script
    main_script_dir = Path(os.path.dirname(__file__)).absolute().expanduser()

    if args['outDir'] == '':
        base_dir = main_script_dir / 'output'
    else:
        base_dir = main_script_dir / args['outDir']

    # if the 'genArduino' flag is set to True, use the arduino generator
    # otherwise, use the meson generator
    if args['genArduino']:
        # generate arduino files
        meson_conf = generators.embedded.arduino.ArduinoConfig(
            '0.7.1',
            main_script_dir,
            base_dir,
            args['printOutFiles']
        )

        meson_conf.generate()

    else:
        # generate all meson build system files
        meson_conf = generators.Cpp17.meson.MesonConfig(
            '0.7.1',
            main_script_dir,
            base_dir,
            args['printOutFiles']
        )

        meson_conf.generate()
