name: "main-ci"

on: 
  push:
    branches-ignore:
      - pages
    tags-ignore:
      - latest

jobs:
  meson_cpp17_matrix:
    uses: ./.github/workflows/cpp17.yaml
    secrets: inherit

  arduino_matix:
    uses: ./.github/workflows/arduino.yaml
    secrets: inherit

  pio_matrix:
    uses: ./.github/workflows/pio.yaml
    secrets: inherit

  python_matrix:
    uses: ./.github/workflows/python.yaml
    secrets: inherit

  releases:
    needs: [ desktop_cpp_meson_matrix, meson_cpp_matrix, arduino_matix, pio_matrix, python_matrix ]
    uses: ./.github/workflows/release.yaml
    secrets: inherit

  push_release_repos:
    needs: [ releases ]
    uses: ./.github/workflows/push_releases.yaml
    secrets: inherit
