name: "main-ci"

on:
  push:
    branches:
      - '*'

jobs:
  build_matrix:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04", "ubuntu-22.04", "macos-latest", "windows-latest"]
        buildType: ["static", "shared"]
        useMsys: [true, false]
        exclude:
          - useMsys: true
            os: "ubuntu-20.04"
          - useMsys: true
            os: "ubuntu-22.04"
          - useMsys: true
            os: "macos-latest"
        include:
          - script_file: "source ./.venv/bin/activate"
            os: "ubuntu-20.04"
          - script_file: "source ./.venv/bin/activate"
            os: "ubuntu-22.04"
          - script_file: "source ./.venv/bin/activate"
            os: "macos-latest"
          - script_file: ".venv/Scripts/activate.ps1"
            os: "windows-latest"
          - setupExtras: "-Db_lto=false -Dgtest:b_lto=false"
            os: "windows-latest"
            
    name: ${{ matrix.os }} ${{ matrix.buildType }} msys ${{ matrix.useMsys }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: default - setup venv
        run: python3 -m venv .venv
      - name: default - install meson and ninja
        run: |
            ${{ matrix.script_file }}
            pip install meson ninja
      - name: default - install pip deps
        if: ${{ !matrix.useMsys }}
        run: |
            ${{ matrix.script_file }}
            pip install -r requirements.txt
            
      - name: generate the sources
        run: | 
            ${{ matrix.script_file }}
            python3 ./getSources.py
            
      - name: default - Prepare MSVC
        if: ${{ !matrix.useMsys && matrix.os == 'windows-latest' }}
        uses: bus1/cabuild/action/msdevshell@v1
        with:
            architecture: x64
      
      - name: default - setup the project
        if: ${{ !matrix.useMsys }}
        run: |
            cd output
            meson setup ${{ matrix.setupExtras }} -Ddefault_library=${{ matrix.buildType }} build
      - name: default - compile the project
        if: ${{ !matrix.useMsys }}
        run: meson compile -C output/build
      - name: default - test the project
        if: ${{ !matrix.useMsys }}
        run: meson test --verbose -C output/build
    
    
      - uses: msys2/setup-msys2@v2
        if: ${{ matrix.useMsys }}
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-python3
            mingw-w64-x86_64-python-pip
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-pkg-config
      
      - name: msys2 - setup the project
        if: ${{ matrix.useMsys }}
        shell: msys2 {0}
        run: |
            cd output
            meson setup ${{ matrix.setupExtras }} -Ddefault_library=${{ matrix.buildType }} build
      - name: msys2 - compile the project
        if: ${{ matrix.useMsys }}
        shell: msys2 {0}
        run: meson compile -C output/build
      - name: msys2 - test the project
        if: ${{ matrix.useMsys }}
        shell: msys2 {0}
        run: meson test --verbose -C output/build
            
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: build-artifact-${{ matrix.os }}-${{ matrix.buildType }}-msys-${{ matrix.useMsys }}
          path: build

  pre-release:
    name: "Pre Release latest"
    runs-on: "ubuntu-22.04"
    needs: build_matrix
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: setup environment and generate sources
        run: |
            python3 -m venv .venv
            source ./.venv/bin/activate
            pip install meson ninja
            pip install -r requirements.txt
            python3 ./genSources.py
      - name: setup and compile sources
        run: |
            mkdir sources
            cd output
            meson setup -Dno_pip_install=true -Dbuild_tests=false -Dprefix=$(pwd)/../sources build
            meson compile -C build
            meson install -C build
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE

