name: "main-ci"

on: 
  push:
    branches-ignore:
      - pages
    tags-ignore:
      - latest

jobs:
  meson_cpp17_matrix:
    uses: ./.github/workflows/cpp17.yaml

  arduino_matix:
    uses: ./.github/workflows/arduino.yaml

  pio_matrix:
    uses: ./.github/workflows/pio.yaml

  releases:
    needs: [ meson_cpp17_matrix, arduino_matix, pio_matrix ]
    uses: ./.github/workflows/release.yaml

  push_release_repos:
    needs: [ releases ]
    uses: ./.github/workflows/push_releases.yaml
