on:
  workflow_call:
    secrets:
      CI_GITHUB_TOKEN:
        required: true
      MESON_DEPLOY_KEY:
        required: true
      ARDUINO_DEPLOY_KEY:
        required: true

jobs:
  upload_matrix:
    runs-on: "ubuntu-22.04"
    strategy:
      fail-fast: false
      matrix:
        generateArgs:
          - name: "cppDesktop"
            args: ""
            args_latest: ""
            repo: "git@github.com:unit-system-exports/unit-system-cppDesktop.git"
          - name: "arduino"
            args: ""
            args_latest: ""
            repo: "git@github.com:unit-system-exports/unit-system-arduino.git"
          - name: "python"
            args: ""
            args_latest: "--no-post-gen"
            repo: "git@github.com:unit-system-exports/unit-system-python.git"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pipenv"
      - name: install pipenv
        run: pip install pipenv
      - name: install script deps
        run: pipenv install
      - name: generate the sources (release)
        if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
        run: pipenv run python3 ./genSources.py --set_version ${{ github.ref_name }} ${{ matrix.generateArgs.args }} -o output ${{ matrix.generateArgs.name }}
      - name: generate the sources (latest)
        if: ${{ !(github.ref_type == 'tag' && startsWith(github.ref_name, 'v')) }}
        run: pipenv run python3 ./genSources.py ${{ matrix.generateArgs.args }} ${{ matrix.generateArgs.args_latest }} -o output ${{ matrix.generateArgs.name }}

      - name: put the meson ssh key to env
        if: ${{ matrix.generateArgs.name == 'cppDesktop' }}
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "ssh_key<<$EOF" >> "$GITHUB_ENV"
          echo "${{ secrets.MESON_DEPLOY_KEY }}" >> "$GITHUB_ENV"
          echo "$EOF" >> "$GITHUB_ENV"
      - name: put the arduino ssh key to env
        if: ${{ matrix.generateArgs.name == 'arduino' }}
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "ssh_key<<$EOF" >> "$GITHUB_ENV"
          echo "${{ secrets.ARDUINO_DEPLOY_KEY }}" >> "$GITHUB_ENV"
          echo "$EOF" >> "$GITHUB_ENV"
      - name: put the arduino ssh key to env
        if: ${{ matrix.generateArgs.name == 'python' }}
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "ssh_key<<$EOF" >> "$GITHUB_ENV"
          echo "${{ secrets.PYTHON_DEPLOY_KEY }}" >> "$GITHUB_ENV"
          echo "$EOF" >> "$GITHUB_ENV"

      - name: commit and push changes to ${{ matrix.generateArgs.name }}
        if: ${{ github.ref_type == 'branch'}}
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: ${{ matrix.generateArgs.repo }}
          BRANCH: ${{ github.ref_name }}
          FOLDER: output
          SSH_PRIVATE_KEY: ${{ env.ssh_key }}
      - name: commit and push changes to ${{ matrix.generateArgs.name }}
        if: ${{ github.ref_type != 'branch' }}
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: ${{ matrix.generateArgs.repo }}
          BRANCH: main
          FOLDER: output
          SSH_PRIVATE_KEY: ${{ env.ssh_key }}
          TAG: ${{ github.ref_name }}
