on:
  workflow_call:
    secrets:
      CI_GITHUB_TOKEN:
        required: true

jobs:
  releases:
    name: "Release"
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          cache: "pipenv"
      - name: setup environment
        run: |
          pipx install meson
          pipx install ninja
          pip install pipenv
          pipenv install
      - name: generate the sources (release)
        if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
        run: pipenv run python3 ./genSources.py --set_version ${{ github.ref_name }} --archive all
      - name: generate the sources (latest)
        if: ${{ !(github.ref_type == 'tag' && startsWith(github.ref_name, 'v')) }}
        run: pipenv run python3 ./genSources.py --archive all
      - name: "Release latest"
        uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}
        with:
          repo_token: "${{ secrets.CI_GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            unit_system_meson.tar.gz
            unit_system_arduino.tar.gz
            unit_system_python.tar.gz

      - name: "release"
        uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
        with:
          repo_token: "${{ secrets.CI_GITHUB_TOKEN }}"
          prerelease: ${{ contains(github.ref_name, '-rc') }}
          files: |
            unit_system_meson.tar.gz
            unit_system_arduino.tar.gz
            unit_system_python.tar.gz